#!/bin/sh
# `location` gets where you are, returns Markdown.
# for OS X ONLY currently
# <3 by @leaskh

# Requirement
# `brew install whereami`
# `brew install jq`
# `brew install qrencode`

init() {
    coordinate=`whereami`
    if [ "$coordinate" = '' ]; then
        echo 'Error getting coordinate, please retry later.'
        exit 1
    fi
    locationJson="https://maps.google.com/maps/api/geocode/json?latlng=${coordinate}${configJson}"
    locationGMap="https://www.google.com/maps/place/${coordinate}"
    locationImgL="https://maps.googleapis.com/maps/api/staticmap?center=${coordinate}${configImage}&markers=|${coordinate}"
    locations=`curl -s "$locationJson"`
    # locations=`proxychains4 curl -s "$locationJson"`
    curLocation=`echo $locations | jq -r '.results[0].formatted_address'`
}

markLink() {
    echo "[${1}](${2} \"${3}\")"
}

markImage() {
    echo "![${1}](${2} \"${3}\")"
}

locationLink() {
    init
    if [ "$curLocation" = 'null' ]; then
        text=$coordinate
    else
        text=$curLocation
    fi
    result=`markLink "$text" "$locationGMap" "$coordinate"`
    echo $result | tee /dev/tty | pbcopy
}

locationImage() {
    init
    if [ "$curLocation" = 'null' ]; then
        text=$coordinate
    else
        text=$curLocation
    fi
    result=`markImage "$text" "$locationImgL" "$coordinate"`
    echo $result | tee /dev/tty | pbcopy
}

locationQrcode() {
    init
    qrencode "$locationGMap" -t UTF8
}

appleMap() {
    init
    open "http://maps.apple.com/?ll=${coordinate}"
}

googleMap() {
    init
    open "$locationGMap"
}

googleMapImg() {
    init
    open "$locationImgL"
}

locationImglnk() {
    init
    if [ "$curLocation" = 'null' ]; then
        text="`locationImage` $coordinate"
    else
        text="`locationImage` $curLocation"
    fi
    result=`markLink "$text"  "$locationImgL" "$coordinate"`
    echo $result | tee /dev/tty | pbcopy
}

showHelp() {
    echo '`location` gets where you are, returns Markdown.'
    echo '================================================'
    echo ''
    echo 'for OS X ONLY currently'
    echo ''
    echo '- link   : Make a Markdown link block with Google Maps'
    echo '- image  : Make a Markdown image block with Google Maps'
    echo '- imglnk : Make a Markdown image link block with Google Maps'
    echo '- qrcode : Show a url qrcode of Google Maps'
    echo '- amap   : Show current location in Apple Maps app'
    echo '- gmap   : Show current location in Google Maps web'
    echo '- gmpimg : Show current location in Google Maps static image'
    echo '- help   : Show this infos'
}

unknowCommand() {
    showHelp
    exit 1
}

# Main logic
configJson='&language=en-US&sensor=true'
configImage='&zoom=13&size=640x480&scale=2'
coordinate=''
locationJson=''
locationGMap=''
locationImgL=''
locations=''
curLocation=''
case "$1" in
    'link'  ) locationLink  ;;
    'image' ) locationImage ;;
    'imglnk') locationImglnk;;
    'qrcode') locationQrcode;;
    'amap'  ) appleMap      ;;
    'gmap'  ) googleMap     ;;
    'gmpimg') googleMapImg  ;;
    'help'  ) showHelp      ;;
    *       ) unknowCommand ;;
esac
exit 0
