#!/bin/sh
# `location` gets where you are, returns Markdown.
# <3 for OS X ONLY currently
# by @leaskh

# Requirement
# `brew install whereami`
# `brew install jq`

init() {
    coordinate=`whereami`
    if [ "$coordinate" = '' ]; then
        echo 'Error getting coordinate, please retry later.'
        exit 1
    fi
    locationJson="https://maps.google.com/maps/api/geocode/json?latlng=${coordinate}${configJson}"
    locationGMap="https://www.google.com/maps/place/${coordinate}"
    locationImgL="https://maps.googleapis.com/maps/api/staticmap?center=${coordinate}${configImage}&markers=|${coordinate}"
    locations=`curl -s "$locationJson"`
    # locations=`proxychains4 curl -s "$locationJson"`
    curLocation=`echo $locations | jq -r '.results[0].formatted_address'`
}

markLink() {
    echo "[${1}](${2} \"${3}\")"
}

markImage() {
    echo "![${1}](${2} \"${3}\")"
}

locationLink() {
    init
    if [ "$curLocation" = 'null' ]; then
        text=$coordinate
    else
        text=$curLocation
    fi
    echo `markLink "$text" "$locationGMap" "$coordinate"`
}

locationImage() {
    init
    if [ "$curLocation" = 'null' ]; then
        text=$coordinate
    else
        text=$curLocation
    fi
    echo `markImage "$text" "$locationImgL" "$coordinate"`
}

locationImglnk() {
    init
    if [ "$curLocation" = 'null' ]; then
        text="`locationImage` $coordinate"
    else
        text="`locationImage` $curLocation"
    fi
    echo `markLink "$text"  "$locationImgL" "$coordinate"`
}

showHelp() {
    echo '`location` gets where you are, returns Markdown.'
    echo '================================================'
    echo '<3 for OS X ONLY currently'
    echo ''
    echo '- link   : Make Markdown location link block'
    echo '- image  : Make Markdown location image block'
    echo '- imglnk : Make Markdown location link block with image'
    echo '- help   : Show this infos'
}

unknowCommand() {
    showHelp
    exit 1
}

# Main logic
configJson='&language=en-US&sensor=true'
configImage='&zoom=13&size=640x480&scale=2'
coordinate=''
locationJson=''
locationGMap=''
locationImgL=''
locations=''
curLocation=''
case "$1" in
    'link'  ) locationLink  ;;
    'image' ) locationImage ;;
    'imglnk') locationImglnk;;
    'help'  ) showHelp      ;;
    *       ) unknowCommand ;;
esac
exit 0
